import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { formatIssues, hasExactPathCase, readJson, scanSourceForBrowserContract, scanSourceForProxyContract, validateProject } from '../src/validation/project.js';

test('validateProject accepts legacy workers without output_schema.json as warnings', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-'));
  fs.writeFileSync(path.join(dir, 'main.js'), '');
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
  }));
  fs.writeFileSync(path.join(dir, 'sdk.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_grpc_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'input_schema.json'), JSON.stringify({
    b: 'items',
    properties: [
      { name: 'items', type: 'array', editor: 'stringList', default: [] },
    ],
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, true);
  assert.equal(result.issues.some((issue) => issue.severity === 'error'), false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_output_schema_legacy'), true);
});

test('validateProject warns when README.md is missing from upload-ready workers', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, true);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_readme'), true);
});

test('validateProject rejects required files whose casing differs from the documented upload structure', () => {
  const dir = makeGoProject();
  fs.renameSync(path.join(dir, 'GoSdk'), path.join(dir, 'gosdk'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'required_file_case_mismatch');

  assert.equal(result.ok, false);
  assert.equal(Boolean(issue), true);
  assert.equal(issue.evidence.expected_path, 'GoSdk/sdk.go');
  assert.equal(issue.evidence.observed_path, 'gosdk/sdk.go');
  assert.deepEqual(issue.docs, ['worker-definition/project-structure.md', 'deployment.md']);
});

test('validateProject warns when README.md casing differs from the documented project structure', () => {
  const dir = makeGoProject();
  fs.writeFileSync(path.join(dir, 'Readme.md'), '# Test\n');

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'readme_file_case_mismatch');

  assert.equal(result.ok, true);
  assert.equal(Boolean(issue), true);
  assert.equal(issue.evidence.expected_path, 'README.md');
  assert.equal(issue.evidence.observed_path, 'Readme.md');
  assert.equal(result.issues.some((item) => item.code === 'missing_readme'), false);
});

test('hasExactPathCase checks each path segment without relying on case-insensitive filesystem lookup', () => {
  const dir = makeGoProject();

  assert.equal(hasExactPathCase(dir, 'GoSdk/sdk.go'), true);
  assert.equal(hasExactPathCase(dir, 'gosdk/sdk.go'), false);
  assert.equal(hasExactPathCase(dir, 'GoSdk/SDK.go'), false);
});

test('readJson accepts UTF-8 BOM files generated by Windows PowerShell', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-json-'));
  const file = path.join(dir, 'input.json');
  fs.writeFileSync(file, '\ufeff{"ok":true}', 'utf8');

  assert.deepEqual(readJson(file), { ok: true });
});

test('validateProject rejects Node workers missing SDK runtime dependencies', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      'google-protobuf': '^4.0.2',
    },
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_runtime_dependency' && /@grpc\/grpc-js/.test(issue.message)), true);
});

test('validateProject rejects Node SDK runtime dependencies declared only as devDependencies', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    devDependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.filter((issue) => issue.code === 'missing_runtime_dependency').length, 2);
});

test('validateProject errors on Node package fields that break CoreClaw SDK', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    main: 'src/index.js',
    type: 'module',
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'node_package_main_not_main_js' && issue.severity === 'error'), true);
  assert.equal(result.issues.some((issue) => issue.code === 'node_package_type_not_commonjs' && issue.severity === 'error'), true);
});

test('validateProject warns when Node source imports undeclared runtime dependencies', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
      'puppeteer-core': '^24.0.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), [
    "const axios = require('axios')",
    "const grpc = require('@grpc/grpc-js/build/src/index')",
    "import('puppeteer-core')",
    "require('./helper')",
    "require('node:fs')",
    'const auth = process.env.PROXY_AUTH',
    'const domain = process.env.PROXY_DOMAIN',
    '',
  ].join('\n'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'node_dependency_not_declared');

  assert.equal(result.ok, true);
  assert.equal(Boolean(issue), true);
  assert.deepEqual(issue.evidence.missing_packages, ['axios']);
  assert.deepEqual(issue.evidence.import_files, ['main.js']);
  assert.deepEqual(issue.evidence.package_json_sections_checked, ['dependencies', 'optionalDependencies']);
  assert.match(issue.message, /axios \(main\.js\)/);
  
  assert.match(issue.remediation, /dependencies or optionalDependencies/);
});

test('validateProject treats devDependencies-only Node imports as undeclared for platform runtime', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
    devDependencies: {
      axios: '^1.7.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), "const axios = require('axios')\n");

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'node_dependency_not_declared' && issue.evidence.missing_packages.includes('axios')), true);
});

test('validateProject accepts declared Node optional dependencies and ignores builtins and local imports', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
    optionalDependencies: {
      'puppeteer-core': '^24.0.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), [
    "const fs = require('fs')",
    "const timers = require('node:timers/promises')",
    "const local = require('./helper')",
    "const puppeteer = require('puppeteer-core')",
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'helper.js'), "module.exports = {}\n");

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'node_dependency_not_declared'), false);
});

test('validateProject errors when HTTP workers do not read CoreClaw proxy env', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
      axios: '^1.7.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), [
    "const axios = require('axios')",
    'async function main() {',
    "  await axios.get('https://example.com')",
    '}',
    'main()',
    '',
  ].join('\n'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'http_proxy_env_not_used');
  const formatted = formatIssues(result.issues);

  assert.equal(result.ok, false);
  assert.equal(issue.severity, 'error');
  assert.equal(Boolean(issue && /PROXY_AUTH and PROXY_DOMAIN/.test(issue.message)), true);
  assert.equal(issue.severity, 'error');
  assert.deepEqual(issue.docs, ['worker-definition/platform-features/proxy-support.md']);
  assert.deepEqual(issue.evidence.missing_env, ['PROXY_AUTH', 'PROXY_DOMAIN']);
  assert.deepEqual(issue.evidence.http_client_files, ['main.js']);
  assert.match(issue.remediation, /socks5:\/\/PROXY_AUTH@PROXY_DOMAIN/);
  assert.match(formatted, /Docs: worker-definition\/platform-features\/proxy-support\.md/);
  assert.match(formatted, /Evidence: HTTP client files=main\.js; missing env=PROXY_AUTH, PROXY_DOMAIN/);
  assert.match(formatted, /Fix: Read PROXY_AUTH and PROXY_DOMAIN/);
});

test('validateProject accepts HTTP workers that read split SOCKS5 proxy env in helper modules', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
      axios: '^1.7.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), "require('./client')\n");
  fs.writeFileSync(path.join(dir, 'client.js'), [
    "const axios = require('axios')",
    'const proxyAuth = process.env.PROXY_AUTH',
    'const proxyDomain = process.env.PROXY_DOMAIN',
    'const proxyUrl = proxyAuth && proxyDomain ? `socks5://${proxyAuth}@${proxyDomain}` : null',
    "axios.get('https://example.com', { proxy: false, proxyUrl })",
    '',
  ].join('\n'));

  const scan = scanSourceForProxyContract(dir, 'node');
  const result = validateProject(dir);

  assert.equal(scan.usesHttpClient, true);
  assert.equal(scan.readsProxyAuth, true);
  assert.equal(scan.readsProxyDomain, true);
  assert.equal(result.issues.some((issue) => issue.code === 'http_proxy_env_not_used'), false);
});

test('validateProject does not treat browser CDP workers as direct HTTP proxy workers', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
      'puppeteer-core': '^24.0.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), [
    "const puppeteer = require('puppeteer-core')",
    'const auth = process.env.PROXY_AUTH',
    'const chromeWs = process.env.ChromeWs',
    'async function main() {',
    '  await puppeteer.connect({ browserWSEndpoint: `ws://${auth}@${chromeWs}` })',
    '}',
    'main()',
    '',
  ].join('\n'));

  const result = validateProject(dir);

  assert.equal(result.ok, true);
  assert.equal(result.issues.some((issue) => issue.code === 'http_proxy_env_not_used'), false);
  assert.equal(result.issues.some((issue) => issue.code === 'browser_endpoint_env_not_used'), false);
});

test('validateProject warns when browser automation does not read CoreClaw browser endpoint env', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
      'puppeteer-core': '^24.0.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), [
    "const puppeteer = require('puppeteer-core')",
    'async function main() {',
    '  const browser = await puppeteer.launch({ headless: true })',
    '  await browser.close()',
    '}',
    'main()',
    '',
  ].join('\n'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'browser_endpoint_env_not_used');
  const formatted = formatIssues(result.issues);

  assert.equal(result.ok, true);
  assert.equal(Boolean(issue), true);
  assert.deepEqual(issue.evidence.browser_client_files, ['main.js']);
  assert.deepEqual(issue.evidence.missing_env, ['PROXY_AUTH', 'ChromeWs/ChromeHttp/LightpandaDomain']);
  assert.match(issue.remediation, /ChromeWs, ChromeHttp, or LightpandaDomain/);
  assert.match(formatted, /Docs: worker-definition\/browser-automation\/overview\.md/);
});

test('validateProject accepts Lightpanda workers using bracket env access', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'playwright>=1.52.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import os',
    'from playwright.async_api import async_playwright',
    '',
    'async def run():',
    '    auth = os.environ["PROXY_AUTH"]',
    '    endpoint = os.environ["LightpandaDomain"]',
    '    async with async_playwright() as playwright:',
    '        browser = await playwright.chromium.connect_over_cdp(endpoint, headers={"Authorization": auth})',
    '        await browser.close()',
    '',
  ].join('\n'));

  const scan = scanSourceForBrowserContract(dir, 'python');
  const result = validateProject(dir);

  assert.equal(scan.usesBrowserAutomation, true);
  assert.equal(scan.readsProxyAuth, true);
  assert.equal(scan.readsAnyBrowserEndpoint, true);
  assert.equal(result.issues.some((issue) => issue.code === 'browser_endpoint_env_not_used'), false);
});

test('validateProject warns about runtime table header drift', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
  }));
  fs.writeFileSync(path.join(dir, 'output_schema.json'), JSON.stringify([
    { name: 'title', type: 'string' },
    { name: 'scraped_at', type: 'string' },
    { name: 'count', type: 'integer' },
    { name: 'enabled', type: 'boolean' },
  ]));

  const result = validateProject(dir, {
    tableHeaders: [
      { label: 'Title', key: 'title', format: 'text' },
      { label: 'Scraped At', key: 'scraped_at', format: 'datetime' },
      { label: 'Count', key: 'count', format: 'text' },
      { label: 'Missing key', key: '', format: 'text' },
      { label: 'Bad format', key: 'enabled', format: 'date' },
      { label: 'Extra', key: 'extra', format: 'text' },
    ],
  });

  assert.equal(result.ok, true);
  assert.deepEqual(result.issues.filter((issue) => issue.code?.startsWith('runtime_header_')).map((issue) => issue.code), [
    'runtime_header_format_mismatch',
    'runtime_header_missing_key',
    'runtime_header_unsupported_format',
    'runtime_header_not_in_output_schema',
  ]);
});

test('validateProject rejects Python workers missing SDK runtime dependencies', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-python-'));
  for (const file of ['main.py', 'sdk.py', 'sdk_pb2.py', 'sdk_pb2_grpc.py']) {
    fs.writeFileSync(path.join(dir, file), '');
  }
  fs.writeFileSync(path.join(dir, 'requirements.txt'), 'protobuf>=5.29.0\n');
  writeInputSchema(dir);

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_runtime_dependency' && /grpcio/.test(issue.message)), true);
});

test('validateProject warns when Python source imports undeclared third-party dependencies', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'beautifulsoup4>=4.12.0',
    'playwright>=1.40.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import json, os',
    'import requests',
    'from bs4 import BeautifulSoup',
    'from playwright.async_api import async_playwright',
    'proxy_auth = os.environ.get("PROXY_AUTH")',
    'proxy_domain = os.environ.get("PROXY_DOMAIN")',
    'from helper import build_url',
    'from sdk import CoreSDK',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'helper.py'), 'def build_url(): return "https://example.com"\n');

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'python_dependency_not_declared');

  assert.equal(Boolean(issue), true);
  assert.deepEqual(issue.evidence.missing_packages, ['requests']);
  assert.deepEqual(issue.evidence.import_files, ['main.py']);
  assert.deepEqual(issue.evidence.requirements_file, 'requirements.txt');
  assert.match(issue.message, /requests \(main\.py\)/);
  
  assert.match(issue.remediation, /requirements\.txt/);
});

test('validateProject scans Python dependencies reachable from main.py and ignores standalone tools and tests', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'requests>=2.32.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import unicodedata',
    'from helper import run',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'helper.py'), 'import requests\n');
  fs.writeFileSync(path.join(dir, 'remote_verify.py'), 'import workflow_optimize\n');
  fs.mkdirSync(path.join(dir, 'test'));
  fs.writeFileSync(path.join(dir, 'test', 'test_worker.py'), 'import pytest\n');

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'python_dependency_not_declared'), false);
});

test('validateProject accepts declared Python mapped packages and ignores local modules and SDK files', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'beautifulsoup4>=4.12.0',
    'playwright-stealth>=1.0.6',
    'opencv-python>=4.10.0',
    'PySocks>=1.7.1',
    'XClientTransaction==1.0.3',
    'python-jobspy>=1.1.80',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import csv',
    'import cv2',
    'import socks',
    'from jobspy import scrape_jobs',
    'from bs4 import BeautifulSoup',
    'from playwright_stealth import stealth_async',
    'from x_client_transaction import ClientTransaction',
    'from local_pkg import run',
    '',
  ].join('\n'));
  fs.mkdirSync(path.join(dir, 'local_pkg'));
  fs.writeFileSync(path.join(dir, 'local_pkg', '__init__.py'), 'def run(): pass\n');
  fs.writeFileSync(path.join(dir, 'sdk.py'), 'import grpc\nfrom google.protobuf import empty_pb2\n');

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'python_dependency_not_declared'), false);
});

test('validateProject ignores Python test sources when checking runtime dependencies', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    '',
  ].join('\n'));
  fs.mkdirSync(path.join(dir, 'tests'));
  fs.writeFileSync(path.join(dir, 'tests', 'test_worker.py'), [
    'import pytest',
    'import pandas as pd',
    '',
  ].join('\n'));

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'python_dependency_not_declared'), false);
});

test('validateProject rejects Go workers missing SDK runtime dependencies', () => {
  const dir = makeGoProject();
  fs.writeFileSync(path.join(dir, 'go.mod'), 'module example\n\ngo 1.23\n\nrequire google.golang.org/protobuf v1.36.6\n');

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_runtime_dependency' && /google.golang.org\/grpc/.test(issue.message)), true);
});

test('validateProject rejects Go workers with missing SDK dependency checksums', () => {
  const dir = makeGoProject();
  fs.writeFileSync(path.join(dir, 'go.sum'), 'google.golang.org/protobuf v1.36.6 h1:fixture=\n');

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'go_missing_module_checksum' && /google.golang.org\/grpc/.test(issue.message)), true);
});


test('validateProject errors when Python uses socks5 proxy but PySocks is missing', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'requests>=2.32.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import os',
    'import requests',
    '',
    'proxyDomain = os.environ.get("PROXY_DOMAIN")',
    'proxyAuth = os.environ.get("PROXY_AUTH")',
    'proxy_url = f"socks5://{proxyAuth}@{proxyDomain}"',
    'resp = requests.get("https://example.com", proxies={"http": proxy_url, "https": proxy_url})',
    '',
  ].join('\n'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'missing_socks_proxy_dependency');

  assert.equal(result.ok, false);
  assert.equal(Boolean(issue), true);
  assert.equal(issue.severity, 'error');
  assert.match(issue.message, /PySocks/);
  assert.deepEqual(issue.docs, ['worker-definition/platform-features/proxy-support.md']);
});

test('validateProject accepts Python socks5 proxy when PySocks is declared', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'requests>=2.32.0',
    'PySocks>=1.7.1',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import os',
    'import requests',
    '',
    'proxyDomain = os.environ.get("PROXY_DOMAIN")',
    'proxyAuth = os.environ.get("PROXY_AUTH")',
    'proxy_url = f"socks5://{proxyAuth}@{proxyDomain}"',
    'resp = requests.get("https://example.com", proxies={"http": proxy_url, "https": proxy_url})',
    '',
  ].join('\n'));

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'missing_socks_proxy_dependency'), false);
});

test('validateProject does not require PySocks for curl_cffi requests aliases', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'curl_cffi==0.13.0',
    'requests>=2.32.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'proxy_utils.py'), [
    'import os',
    '',
    'def get_runtime_proxies():',
    '    proxy_domain = os.environ.get("PROXY_DOMAIN")',
    '    proxy_auth = os.environ.get("PROXY_AUTH")',
    '    proxy_url = f"socks5://{proxy_auth}@{proxy_domain}"',
    '    return {"http": proxy_url, "https": proxy_url}',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'from curl_cffi import requests as curl_requests',
    'from proxy_utils import get_runtime_proxies',
    '',
    'session = curl_requests.Session()',
    'resp = session.get("https://example.com", proxies=get_runtime_proxies())',
    '',
  ].join('\n'));

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'missing_socks_proxy_dependency'), false);
});

test('validateProject warns about hardcoded User-Agent strings', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'requests>=2.32.0',
    'PySocks>=1.7.1',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import os',
    'import requests',
    '',
    'headers = {',
    '    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"',
    '}',
    'resp = requests.get("https://example.com", headers=headers)',
    '',
  ].join('\n'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'hardcoded_user_agent');

  assert.equal(Boolean(issue), true);
  assert.equal(issue.severity, 'warn');
  assert.match(issue.message, /hardcoded User-Agent/);
});

test('validateProject errors when HTTP worker does not use proxy (upgraded from warn)', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf>=6.31.0',
    'requests>=2.32.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), [
    'import requests',
    'resp = requests.get("https://example.com")',
    '',
  ].join('\n'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'http_proxy_env_not_used');

  assert.equal(result.ok, false);
  assert.equal(Boolean(issue), true);
  assert.equal(issue.severity, 'error');
  assert.match(issue.message, /isolated network sandbox/);
});

test('validateProject errors when Node uses socks-proxy-agent but not declared in package.json', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
      axios: '^1.7.0',
    },
  }));
  fs.writeFileSync(path.join(dir, 'main.js'), [
    "const axios = require('axios')",
    "const { SocksProxyAgent } = require('socks-proxy-agent')",
    'async function main() {',
    "  const agent = new SocksProxyAgent('socks5://user:pass@proxy.example.com')",
    "  await axios.get('https://example.com', { httpAgent: agent, httpsAgent: agent, proxy: false })",
    '}',
    'main()',
    '',
  ].join('\n'));

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'missing_socks_proxy_dependency');

  assert.equal(Boolean(issue), true);
  assert.equal(issue.severity, 'error');
  assert.match(issue.message, /socks-proxy-agent/);
});

test('validateProject warns when Python protobuf version is not pinned', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio>=1.80.0',
    'protobuf',
    'requests>=2.32.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), 'import requests\n');

  const result = validateProject(dir);
  const issue = result.issues.find((item) => item.code === 'protobuf_version_not_pinned');

  assert.equal(Boolean(issue), true);
  assert.equal(issue.severity, 'warn');
  assert.match(issue.message, /pinned version/);
});

test('validateProject accepts pinned protobuf version', () => {
  const dir = makePythonProject();
  fs.writeFileSync(path.join(dir, 'requirements.txt'), [
    'grpcio==1.80.0',
    'protobuf==5.29.0',
    'requests==2.32.0',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'main.py'), 'import requests\n');

  const result = validateProject(dir);

  assert.equal(result.issues.some((issue) => issue.code === 'protobuf_version_not_pinned'), false);
});


function makeNodeProject() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-node-'));
  fs.writeFileSync(path.join(dir, 'main.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_grpc_pb.js'), '');
  writeInputSchema(dir);
  return dir;
}

function makePythonProject() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-python-'));
  for (const file of ['main.py', 'sdk.py', 'sdk_pb2.py', 'sdk_pb2_grpc.py']) {
    fs.writeFileSync(path.join(dir, file), '');
  }
  writeInputSchema(dir);
  return dir;
}

function makeGoProject() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-go-'));
  fs.mkdirSync(path.join(dir, 'GoSdk'));
  fs.writeFileSync(path.join(dir, 'main.go'), '');
  fs.writeFileSync(path.join(dir, 'go.mod'), [
    'module example',
    '',
    'go 1.23',
    '',
    'require (',
    '  google.golang.org/grpc v1.75.1',
    '  google.golang.org/protobuf v1.36.6',
    ')',
    '',
  ].join('\n'));
  fs.writeFileSync(path.join(dir, 'go.sum'), [
    'google.golang.org/grpc v1.75.1 h1:fixture=',
    'google.golang.org/protobuf v1.36.6 h1:fixture=',
    '',
  ].join('\n'));
  for (const file of ['sdk.go', 'sdk.pb.go', 'sdk_grpc.pb.go']) {
    fs.writeFileSync(path.join(dir, 'GoSdk', file), '');
  }
  writeInputSchema(dir);
  return dir;
}

function writeInputSchema(dir) {
  fs.writeFileSync(path.join(dir, 'input_schema.json'), JSON.stringify({
    b: 'items',
    properties: [
      { name: 'items', type: 'array', editor: 'stringList', default: [] },
    ],
  }));
}
