import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { readJson, validateProject } from '../src/validation/project.js';

test('validateProject accepts legacy workers without output_schema.json as warnings', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-'));
  fs.writeFileSync(path.join(dir, 'main.js'), '');
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
  }));
  fs.writeFileSync(path.join(dir, 'sdk.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_grpc_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'input_schema.json'), JSON.stringify({
    b: 'items',
    properties: [
      { name: 'items', type: 'array', editor: 'stringList', default: [] },
    ],
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, true);
  assert.equal(result.issues.some((issue) => issue.severity === 'error'), false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_output_schema_legacy'), true);
});

test('readJson accepts UTF-8 BOM files generated by Windows PowerShell', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-json-'));
  const file = path.join(dir, 'input.json');
  fs.writeFileSync(file, '\ufeff{"ok":true}', 'utf8');

  assert.deepEqual(readJson(file), { ok: true });
});

test('validateProject rejects Node workers missing SDK runtime dependencies', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    dependencies: {
      'google-protobuf': '^4.0.2',
    },
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_runtime_dependency' && /@grpc\/grpc-js/.test(issue.message)), true);
});

test('validateProject rejects Node SDK runtime dependencies declared only as devDependencies', () => {
  const dir = makeNodeProject();
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify({
    devDependencies: {
      '@grpc/grpc-js': '^1.14.3',
      'google-protobuf': '^4.0.2',
    },
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.filter((issue) => issue.code === 'missing_runtime_dependency').length, 2);
});

test('validateProject rejects Python workers missing SDK runtime dependencies', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-python-'));
  for (const file of ['main.py', 'sdk.py', 'sdk_pb2.py', 'sdk_pb2_grpc.py']) {
    fs.writeFileSync(path.join(dir, file), '');
  }
  fs.writeFileSync(path.join(dir, 'requirements.txt'), 'protobuf>=5.29.0\n');
  writeInputSchema(dir);

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_runtime_dependency' && /grpcio/.test(issue.message)), true);
});

test('validateProject rejects Go workers missing SDK runtime dependencies', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-go-'));
  fs.mkdirSync(path.join(dir, 'GoSdk'));
  fs.writeFileSync(path.join(dir, 'main.go'), '');
  fs.writeFileSync(path.join(dir, 'go.sum'), '');
  fs.writeFileSync(path.join(dir, 'go.mod'), 'module example\n\ngo 1.23\n\nrequire google.golang.org/protobuf v1.36.6\n');
  for (const file of ['sdk.go', 'sdk.pb.go', 'sdk_grpc.pb.go']) {
    fs.writeFileSync(path.join(dir, 'GoSdk', file), '');
  }
  writeInputSchema(dir);

  const result = validateProject(dir);

  assert.equal(result.ok, false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_runtime_dependency' && /google.golang.org\/grpc/.test(issue.message)), true);
});

function makeNodeProject() {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-node-'));
  fs.writeFileSync(path.join(dir, 'main.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_grpc_pb.js'), '');
  writeInputSchema(dir);
  return dir;
}

function writeInputSchema(dir) {
  fs.writeFileSync(path.join(dir, 'input_schema.json'), JSON.stringify({
    b: 'items',
    properties: [
      { name: 'items', type: 'array', editor: 'stringList', default: [] },
    ],
  }));
}
