import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { readJson, validateProject } from '../src/validation/project.js';

test('validateProject accepts legacy workers without output_schema.json as warnings', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-project-'));
  fs.writeFileSync(path.join(dir, 'main.js'), '');
  fs.writeFileSync(path.join(dir, 'package.json'), '{}');
  fs.writeFileSync(path.join(dir, 'sdk.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'sdk_grpc_pb.js'), '');
  fs.writeFileSync(path.join(dir, 'input_schema.json'), JSON.stringify({
    b: 'items',
    properties: [
      { name: 'items', type: 'array', editor: 'stringList', default: [] },
    ],
  }));

  const result = validateProject(dir);

  assert.equal(result.ok, true);
  assert.equal(result.issues.some((issue) => issue.severity === 'error'), false);
  assert.equal(result.issues.some((issue) => issue.code === 'missing_output_schema_legacy'), true);
});

test('readJson accepts UTF-8 BOM files generated by Windows PowerShell', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'coreclaw-json-'));
  const file = path.join(dir, 'input.json');
  fs.writeFileSync(file, '\ufeff{"ok":true}', 'utf8');

  assert.deepEqual(readJson(file), { ok: true });
});
