// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: sdk.proto

package coresdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InputJSONStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	JsonString    string                 `protobuf:"bytes,2,opt,name=jsonString,proto3" json:"jsonString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputJSONStringResponse) Reset() {
	*x = InputJSONStringResponse{}
	mi := &file_sdk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputJSONStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputJSONStringResponse) ProtoMessage() {}

func (x *InputJSONStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputJSONStringResponse.ProtoReflect.Descriptor instead.
func (*InputJSONStringResponse) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{0}
}

func (x *InputJSONStringResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InputJSONStringResponse) GetJsonString() string {
	if x != nil {
		return x.JsonString
	}
	return ""
}

type TableHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []*TableHeaderItem     `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableHeader) Reset() {
	*x = TableHeader{}
	mi := &file_sdk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableHeader) ProtoMessage() {}

func (x *TableHeader) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableHeader.ProtoReflect.Descriptor instead.
func (*TableHeader) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{1}
}

func (x *TableHeader) GetHeaders() []*TableHeaderItem {
	if x != nil {
		return x.Headers
	}
	return nil
}

type TableHeaderItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Label string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Key   string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// string format = 3 [(allowed_values) = "text,image"];
	Format        string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableHeaderItem) Reset() {
	*x = TableHeaderItem{}
	mi := &file_sdk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableHeaderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableHeaderItem) ProtoMessage() {}

func (x *TableHeaderItem) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableHeaderItem.ProtoReflect.Descriptor instead.
func (*TableHeaderItem) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{2}
}

func (x *TableHeaderItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TableHeaderItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *TableHeaderItem) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonString    string                 `protobuf:"bytes,1,opt,name=jsonString,proto3" json:"jsonString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_sdk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{3}
}

func (x *Data) GetJsonString() string {
	if x != nil {
		return x.JsonString
	}
	return ""
}

type LogBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           string                 `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBody) Reset() {
	*x = LogBody{}
	mi := &file_sdk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBody) ProtoMessage() {}

func (x *LogBody) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBody.ProtoReflect.Descriptor instead.
func (*LogBody) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{4}
}

func (x *LogBody) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_sdk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_sdk_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var file_sdk_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50000,
		Name:          "coresdk.allowed_values",
		Tag:           "bytes,50000,opt,name=allowed_values",
		Filename:      "sdk.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string allowed_values = 50000;
	E_AllowedValues = &file_sdk_proto_extTypes[0]
)

var File_sdk_proto protoreflect.FileDescriptor

const file_sdk_proto_rawDesc = "" +
	"\n" +
	"\tsdk.proto\x12\acoresdk\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/descriptor.proto\"M\n" +
	"\x17InputJSONStringResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x1e\n" +
	"\n" +
	"jsonString\x18\x02 \x01(\tR\n" +
	"jsonString\"A\n" +
	"\vTableHeader\x122\n" +
	"\aheaders\x18\x01 \x03(\v2\x18.coresdk.TableHeaderItemR\aheaders\"Q\n" +
	"\x0fTableHeaderItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"&\n" +
	"\x04Data\x12\x1e\n" +
	"\n" +
	"jsonString\x18\x01 \x01(\tR\n" +
	"jsonString\"\x1b\n" +
	"\aLogBody\x12\x10\n" +
	"\x03log\x18\x01 \x01(\tR\x03log\"8\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2]\n" +
	"\tParameter\x12P\n" +
	"\x12GetInputJSONString\x12\x16.google.protobuf.Empty\x1a .coresdk.InputJSONStringResponse\"\x002u\n" +
	"\x06Result\x12;\n" +
	"\x0eSetTableHeader\x12\x14.coresdk.TableHeader\x1a\x11.coresdk.Response\"\x00\x12.\n" +
	"\bPushData\x12\r.coresdk.Data\x1a\x11.coresdk.Response\"\x002\xc3\x01\n" +
	"\x03Log\x12.\n" +
	"\x05Debug\x12\x10.coresdk.LogBody\x1a\x11.coresdk.Response\"\x00\x12-\n" +
	"\x04Info\x12\x10.coresdk.LogBody\x1a\x11.coresdk.Response\"\x00\x12-\n" +
	"\x04Warn\x12\x10.coresdk.LogBody\x1a\x11.coresdk.Response\"\x00\x12.\n" +
	"\x05Error\x12\x10.coresdk.LogBody\x1a\x11.coresdk.Response\"\x00:F\n" +
	"\x0eallowed_values\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\tR\rallowedValuesB\fZ\n" +
	"./;coresdkb\x06proto3"

var (
	file_sdk_proto_rawDescOnce sync.Once
	file_sdk_proto_rawDescData []byte
)

func file_sdk_proto_rawDescGZIP() []byte {
	file_sdk_proto_rawDescOnce.Do(func() {
		file_sdk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_proto_rawDesc), len(file_sdk_proto_rawDesc)))
	})
	return file_sdk_proto_rawDescData
}

var file_sdk_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sdk_proto_goTypes = []any{
	(*InputJSONStringResponse)(nil),   // 0: coresdk.InputJSONStringResponse
	(*TableHeader)(nil),               // 1: coresdk.TableHeader
	(*TableHeaderItem)(nil),           // 2: coresdk.TableHeaderItem
	(*Data)(nil),                      // 3: coresdk.Data
	(*LogBody)(nil),                   // 4: coresdk.LogBody
	(*Response)(nil),                  // 5: coresdk.Response
	(*descriptorpb.FieldOptions)(nil), // 6: google.protobuf.FieldOptions
	(*emptypb.Empty)(nil),             // 7: google.protobuf.Empty
}
var file_sdk_proto_depIdxs = []int32{
	2, // 0: coresdk.TableHeader.headers:type_name -> coresdk.TableHeaderItem
	6, // 1: coresdk.allowed_values:extendee -> google.protobuf.FieldOptions
	7, // 2: coresdk.Parameter.GetInputJSONString:input_type -> google.protobuf.Empty
	1, // 3: coresdk.Result.SetTableHeader:input_type -> coresdk.TableHeader
	3, // 4: coresdk.Result.PushData:input_type -> coresdk.Data
	4, // 5: coresdk.Log.Debug:input_type -> coresdk.LogBody
	4, // 6: coresdk.Log.Info:input_type -> coresdk.LogBody
	4, // 7: coresdk.Log.Warn:input_type -> coresdk.LogBody
	4, // 8: coresdk.Log.Error:input_type -> coresdk.LogBody
	0, // 9: coresdk.Parameter.GetInputJSONString:output_type -> coresdk.InputJSONStringResponse
	5, // 10: coresdk.Result.SetTableHeader:output_type -> coresdk.Response
	5, // 11: coresdk.Result.PushData:output_type -> coresdk.Response
	5, // 12: coresdk.Log.Debug:output_type -> coresdk.Response
	5, // 13: coresdk.Log.Info:output_type -> coresdk.Response
	5, // 14: coresdk.Log.Warn:output_type -> coresdk.Response
	5, // 15: coresdk.Log.Error:output_type -> coresdk.Response
	9, // [9:16] is the sub-list for method output_type
	2, // [2:9] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_proto_init() }
func file_sdk_proto_init() {
	if File_sdk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_proto_rawDesc), len(file_sdk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 1,
			NumServices:   3,
		},
		GoTypes:           file_sdk_proto_goTypes,
		DependencyIndexes: file_sdk_proto_depIdxs,
		MessageInfos:      file_sdk_proto_msgTypes,
		ExtensionInfos:    file_sdk_proto_extTypes,
	}.Build()
	File_sdk_proto = out.File
	file_sdk_proto_goTypes = nil
	file_sdk_proto_depIdxs = nil
}
