// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: sdk.proto

package coresdk

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Parameter_GetInputJSONString_FullMethodName = "/coresdk.Parameter/GetInputJSONString"
)

// ParameterClient is the client API for Parameter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ParameterClient interface {
	GetInputJSONString(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InputJSONStringResponse, error)
}

type parameterClient struct {
	cc grpc.ClientConnInterface
}

func NewParameterClient(cc grpc.ClientConnInterface) ParameterClient {
	return &parameterClient{cc}
}

func (c *parameterClient) GetInputJSONString(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*InputJSONStringResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InputJSONStringResponse)
	err := c.cc.Invoke(ctx, Parameter_GetInputJSONString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParameterServer is the server API for Parameter service.
// All implementations must embed UnimplementedParameterServer
// for forward compatibility.
type ParameterServer interface {
	GetInputJSONString(context.Context, *emptypb.Empty) (*InputJSONStringResponse, error)
	mustEmbedUnimplementedParameterServer()
}

// UnimplementedParameterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParameterServer struct{}

func (UnimplementedParameterServer) GetInputJSONString(context.Context, *emptypb.Empty) (*InputJSONStringResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInputJSONString not implemented")
}
func (UnimplementedParameterServer) mustEmbedUnimplementedParameterServer() {}
func (UnimplementedParameterServer) testEmbeddedByValue()                   {}

// UnsafeParameterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParameterServer will
// result in compilation errors.
type UnsafeParameterServer interface {
	mustEmbedUnimplementedParameterServer()
}

func RegisterParameterServer(s grpc.ServiceRegistrar, srv ParameterServer) {
	// If the following call panics, it indicates UnimplementedParameterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Parameter_ServiceDesc, srv)
}

func _Parameter_GetInputJSONString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParameterServer).GetInputJSONString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Parameter_GetInputJSONString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParameterServer).GetInputJSONString(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Parameter_ServiceDesc is the grpc.ServiceDesc for Parameter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Parameter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coresdk.Parameter",
	HandlerType: (*ParameterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInputJSONString",
			Handler:    _Parameter_GetInputJSONString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk.proto",
}

const (
	Result_SetTableHeader_FullMethodName = "/coresdk.Result/SetTableHeader"
	Result_PushData_FullMethodName       = "/coresdk.Result/PushData"
)

// ResultClient is the client API for Result service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResultClient interface {
	SetTableHeader(ctx context.Context, in *TableHeader, opts ...grpc.CallOption) (*Response, error)
	PushData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error)
}

type resultClient struct {
	cc grpc.ClientConnInterface
}

func NewResultClient(cc grpc.ClientConnInterface) ResultClient {
	return &resultClient{cc}
}

func (c *resultClient) SetTableHeader(ctx context.Context, in *TableHeader, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Result_SetTableHeader_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resultClient) PushData(ctx context.Context, in *Data, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Result_PushData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResultServer is the server API for Result service.
// All implementations must embed UnimplementedResultServer
// for forward compatibility.
type ResultServer interface {
	SetTableHeader(context.Context, *TableHeader) (*Response, error)
	PushData(context.Context, *Data) (*Response, error)
	mustEmbedUnimplementedResultServer()
}

// UnimplementedResultServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResultServer struct{}

func (UnimplementedResultServer) SetTableHeader(context.Context, *TableHeader) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTableHeader not implemented")
}
func (UnimplementedResultServer) PushData(context.Context, *Data) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method PushData not implemented")
}
func (UnimplementedResultServer) mustEmbedUnimplementedResultServer() {}
func (UnimplementedResultServer) testEmbeddedByValue()                {}

// UnsafeResultServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResultServer will
// result in compilation errors.
type UnsafeResultServer interface {
	mustEmbedUnimplementedResultServer()
}

func RegisterResultServer(s grpc.ServiceRegistrar, srv ResultServer) {
	// If the following call panics, it indicates UnimplementedResultServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Result_ServiceDesc, srv)
}

func _Result_SetTableHeader_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableHeader)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResultServer).SetTableHeader(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Result_SetTableHeader_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResultServer).SetTableHeader(ctx, req.(*TableHeader))
	}
	return interceptor(ctx, in, info, handler)
}

func _Result_PushData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Data)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResultServer).PushData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Result_PushData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResultServer).PushData(ctx, req.(*Data))
	}
	return interceptor(ctx, in, info, handler)
}

// Result_ServiceDesc is the grpc.ServiceDesc for Result service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Result_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coresdk.Result",
	HandlerType: (*ResultServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTableHeader",
			Handler:    _Result_SetTableHeader_Handler,
		},
		{
			MethodName: "PushData",
			Handler:    _Result_PushData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk.proto",
}

const (
	Log_Debug_FullMethodName = "/coresdk.Log/Debug"
	Log_Info_FullMethodName  = "/coresdk.Log/Info"
	Log_Warn_FullMethodName  = "/coresdk.Log/Warn"
	Log_Error_FullMethodName = "/coresdk.Log/Error"
)

// LogClient is the client API for Log service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogClient interface {
	Debug(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
	Info(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
	Warn(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
	Error(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error)
}

type logClient struct {
	cc grpc.ClientConnInterface
}

func NewLogClient(cc grpc.ClientConnInterface) LogClient {
	return &logClient{cc}
}

func (c *logClient) Debug(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Log_Debug_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Info(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Log_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Warn(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Log_Warn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logClient) Error(ctx context.Context, in *LogBody, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Log_Error_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LogServer is the server API for Log service.
// All implementations must embed UnimplementedLogServer
// for forward compatibility.
type LogServer interface {
	Debug(context.Context, *LogBody) (*Response, error)
	Info(context.Context, *LogBody) (*Response, error)
	Warn(context.Context, *LogBody) (*Response, error)
	Error(context.Context, *LogBody) (*Response, error)
	mustEmbedUnimplementedLogServer()
}

// UnimplementedLogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogServer struct{}

func (UnimplementedLogServer) Debug(context.Context, *LogBody) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Debug not implemented")
}
func (UnimplementedLogServer) Info(context.Context, *LogBody) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedLogServer) Warn(context.Context, *LogBody) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Warn not implemented")
}
func (UnimplementedLogServer) Error(context.Context, *LogBody) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Error not implemented")
}
func (UnimplementedLogServer) mustEmbedUnimplementedLogServer() {}
func (UnimplementedLogServer) testEmbeddedByValue()             {}

// UnsafeLogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogServer will
// result in compilation errors.
type UnsafeLogServer interface {
	mustEmbedUnimplementedLogServer()
}

func RegisterLogServer(s grpc.ServiceRegistrar, srv LogServer) {
	// If the following call panics, it indicates UnimplementedLogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Log_ServiceDesc, srv)
}

func _Log_Debug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Debug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_Debug_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Debug(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Info(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Warn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Warn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_Warn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Warn(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _Log_Error_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogServer).Error(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Log_Error_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogServer).Error(ctx, req.(*LogBody))
	}
	return interceptor(ctx, in, info, handler)
}

// Log_ServiceDesc is the grpc.ServiceDesc for Log service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Log_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coresdk.Log",
	HandlerType: (*LogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Debug",
			Handler:    _Log_Debug_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Log_Info_Handler,
		},
		{
			MethodName: "Warn",
			Handler:    _Log_Warn_Handler,
		},
		{
			MethodName: "Error",
			Handler:    _Log_Error_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk.proto",
}
