import fs from 'node:fs';
import path from 'node:path';
import { defaultsFromInputSchema } from '../runtime/input.js';
import { CliError } from '../utils/errors.js';
import { repoRoot } from '../utils/paths.js';

const SUPPORTED_LANGUAGES = new Set(['python', 'node', 'go']);

export async function initCommand(target = '.', options = {}) {
  const language = normalizeLanguage(options.language ?? options.lang ?? 'python');
  const projectDir = path.resolve(process.cwd(), target);

  if (fs.existsSync(projectDir) && fs.readdirSync(projectDir).length > 0 && !options.force) {
    throw new CliError(`Target directory is not empty: ${projectDir}. Use --force to write into it.`);
  }

  fs.mkdirSync(projectDir, { recursive: true });
  copyTemplateSdk(language, projectDir);
  writeTemplateProject(language, projectDir, options.name ?? path.basename(projectDir), options);

  console.log(`Created ${language} CoreClaw worker: ${projectDir}`);
  console.log(`Next: coreclaw run ${projectDir}`);
  return projectDir;
}

function normalizeLanguage(language) {
  const value = String(language).toLowerCase();
  if (value === 'js' || value === 'javascript' || value === 'nodejs') {
    return 'node';
  }
  if (!SUPPORTED_LANGUAGES.has(value)) {
    throw new CliError(`Unsupported language "${language}". Use python, node, or go.`);
  }
  return value;
}

function copyTemplateSdk(language, projectDir) {
  const sourceDir = path.join(repoRoot, 'templates', language);
  copyDir(sourceDir, projectDir);
}

function copyDir(sourceDir, targetDir) {
  for (const entry of fs.readdirSync(sourceDir, { withFileTypes: true })) {
    const source = path.join(sourceDir, entry.name);
    const target = path.join(targetDir, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(target, { recursive: true });
      copyDir(source, target);
    } else if (entry.isFile()) {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(source, target);
    }
  }
}

function writeTemplateProject(language, projectDir, name, options = {}) {
  const inputSchema = {
    description: `${name} CoreClaw worker`,
    b: 'startUrls',
    properties: [
      {
        title: 'Start URLs',
        name: 'startUrls',
        type: 'array',
        editor: 'requestList',
        description: 'URLs to process.',
        default: [{ url: 'https://example.com' }],
        required: true,
      },
    ],
  };

  writeJson(path.join(projectDir, 'input_schema.json'), inputSchema);
  if (options.inputExample !== false) {
    writeJson(path.join(projectDir, 'input.example.json'), defaultsFromInputSchema(inputSchema));
  }

  writeJson(path.join(projectDir, 'output_schema.json'), [
    { name: 'url', type: 'string', description: 'URL' },
    { name: 'status', type: 'string', description: 'Status' },
    { name: 'title', type: 'string', description: 'Title' },
  ]);

  if (language === 'python') {
    writeIfMissing(path.join(projectDir, 'requirements.txt'), 'grpcio>=1.71.0\nprotobuf>=5.29.0\n');
    writeIfMissing(path.join(projectDir, 'README.md'), readme(name, 'python'));
    writeIfMissing(path.join(projectDir, 'main.py'), pythonMain());
  } else if (language === 'node') {
    writeJson(path.join(projectDir, 'package.json'), {
      name: slugify(name),
      version: '0.1.0',
      private: true,
      main: 'main.js',
      scripts: { start: 'node main.js' },
      dependencies: {
        '@grpc/grpc-js': '^1.14.3',
        'google-protobuf': '^4.0.2',
      },
    });
    writeIfMissing(path.join(projectDir, 'README.md'), readme(name, 'node'));
    writeIfMissing(path.join(projectDir, 'main.js'), nodeMain());
  } else if (language === 'go') {
    const moduleName = slugify(name);
    writeIfMissing(path.join(projectDir, 'go.mod'), goMod(moduleName));
    writeIfMissing(path.join(projectDir, 'go.sum'), goSum());
    writeIfMissing(path.join(projectDir, 'README.md'), readme(name, 'go'));
    writeIfMissing(path.join(projectDir, 'main.go'), goMain(moduleName));
  }
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function writeIfMissing(filePath, content) {
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content, 'utf8');
  }
}

function slugify(value) {
  const slug = String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return slug || 'coreclaw-worker';
}

function readme(name, language) {
  return `# ${name}\n\nGenerated by CoreClaw CLI.\n\n## Local Run\n\n\`\`\`bash\ncoreclaw run .\n\`\`\`\n\n## Upload Package\n\n\`\`\`bash\ncoreclaw pack .\n\`\`\`\n\nLanguage: ${language}\n`;
}

function pythonMain() {
  return `#!/usr/bin/env python3\nimport asyncio\nfrom sdk import CoreSDK\n\n\nasync def run():\n    input_json = CoreSDK.Parameter.get_input_json_dict()\n    url = input_json.get(\"url\") or (input_json.get(\"startUrls\", [{}])[0].get(\"url\") if input_json.get(\"startUrls\") else \"\")\n\n    CoreSDK.Result.set_table_header([\n        {\"label\": \"URL\", \"key\": \"url\", \"format\": \"text\"},\n        {\"label\": \"Status\", \"key\": \"status\", \"format\": \"text\"},\n        {\"label\": \"Title\", \"key\": \"title\", \"format\": \"text\"},\n    ])\n    CoreSDK.Log.info(f\"Processing {url}\")\n    CoreSDK.Result.push_data({\"url\": url, \"status\": \"success\", \"title\": \"Example Domain\"})\n\n\nif __name__ == \"__main__\":\n    asyncio.run(run())\n`;
}

function nodeMain() {
  return `const coresdk = require('./sdk')\n\nasync function main() {\n  const input = await coresdk.parameter.getInputJSONObject()\n  const url = input.url || (Array.isArray(input.startUrls) && input.startUrls[0] ? input.startUrls[0].url : '')\n\n  await coresdk.result.setTableHeader([\n    { label: 'URL', key: 'url', format: 'text' },\n    { label: 'Status', key: 'status', format: 'text' },\n    { label: 'Title', key: 'title', format: 'text' },\n  ])\n  await coresdk.log.info(\`Processing \${url}\`)\n  await coresdk.result.pushData({ url, status: 'success', title: 'Example Domain' })\n}\n\nmain().catch(async (error) => {\n  try { await coresdk.log.error(error.stack || error.message) } catch {}\n  process.exitCode = 1\n})\n`;
}

function goMod(moduleName) {
  return `module ${moduleName}\n\ngo 1.23\n\nrequire google.golang.org/grpc v1.71.1\n\nrequire google.golang.org/protobuf v1.36.6\n\nrequire (\n\tgolang.org/x/net v0.34.0 // indirect\n\tgolang.org/x/sys v0.29.0 // indirect\n\tgolang.org/x/text v0.21.0 // indirect\n\tgoogle.golang.org/genproto/googleapis/rpc v0.0.0-20250115164207-1a7da9e5054f // indirect\n)\n`;
}

function goSum() {
  return `github.com/go-logr/logr v1.4.2 h1:6pFjapn8bFcIbiKo3XT4j/BhANplGihG6tvd+8rYgrY=\ngithub.com/go-logr/logr v1.4.2/go.mod h1:9T104GzyrTigFIr8wt5mBrctHMim0Nb2HLGrmQ40KvY=\ngithub.com/go-logr/stdr v1.2.2 h1:hSWxHoqTgW2S2qGc0LTAI563KZ5YKYRhT3MFKZMbjag=\ngithub.com/go-logr/stdr v1.2.2/go.mod h1:mMo/vtBO5dYbehREoey6XUKy/eSumjCCveDpRre4VKE=\ngithub.com/golang/protobuf v1.5.4 h1:i7eJL8qZTpSEXOPTxNKhASYpMn+8e5Q6AdndVa1dWek=\ngithub.com/golang/protobuf v1.5.4/go.mod h1:lnTiLA8Wa4RWRcIUkrtSVa5nRhsEGBg48fD6rSs7xps=\ngithub.com/google/go-cmp v0.6.0 h1:ofyhxvXcZhMsU5ulbFiLKl/XBFqE1GSq7atu8tAmTRI=\ngithub.com/google/go-cmp v0.6.0/go.mod h1:17dUlkBOakJ0+DkrSSNjCkIjxS6bF9zb3elmeNGIjoY=\ngithub.com/google/uuid v1.6.0 h1:NIvaJDMOsjHA8n1jAhLSgzrAzy1Hgr+hNrb57e+94F0=\ngithub.com/google/uuid v1.6.0/go.mod h1:TIyPZe4MgqvfeYDBFedMoGGpEw/LqOeaOT+nhxU+yHo=\ngo.opentelemetry.io/auto/sdk v1.1.0 h1:cH53jehLUN6UFLY71z+NDOiNJqDdPRaXzTel0sJySYA=\ngo.opentelemetry.io/auto/sdk v1.1.0/go.mod h1:3wSPjt5PWp2RhlCcmmOial7AvC4DQqZb7a7wCow3W8A=\ngo.opentelemetry.io/otel v1.34.0 h1:zRLXxLCgL1WyKsPVrgbSdMN4c0FMkDAskSTQP+0hdUY=\ngo.opentelemetry.io/otel v1.34.0/go.mod h1:OWFPOQ+h4G8xpyjgqo4SxJYdDQ/qmRH+wivy7zzx9oI=\ngo.opentelemetry.io/otel/metric v1.34.0 h1:+eTR3U0MyfWjRDhmFMxe2SsW64QrZ84AOhvqS7Y+PoQ=\ngo.opentelemetry.io/otel/metric v1.34.0/go.mod h1:CEDrp0fy2D0MvkXE+dPV7cMi8tWZwX3dmaIhwPOaqHE=\ngo.opentelemetry.io/otel/sdk v1.34.0 h1:95zS4k/2GOy069d321O8jWgYsW3MzVV+KuSPKp7Wr1A=\ngo.opentelemetry.io/otel/sdk v1.34.0/go.mod h1:0e/pNiaMAqaykJGKbi+tSjWfNNHMTxoC9qANsCzbyxU=\ngo.opentelemetry.io/otel/sdk/metric v1.34.0 h1:5CeK9ujjbFVL5c1PhLuStg1wxA7vQv7ce1EK0Gyvahk=\ngo.opentelemetry.io/otel/sdk/metric v1.34.0/go.mod h1:jQ/r8Ze28zRKoNRdkjCZxfs6YvBTG1+YIqyFVFYec5w=\ngo.opentelemetry.io/otel/trace v1.34.0 h1:+ouXS2V8Rd4hp4580a8q23bg0azF2nI8cqLYnC8mh/k=\ngo.opentelemetry.io/otel/trace v1.34.0/go.mod h1:Svm7lSjQD7kG7KJ/MUHPVXSDGz2OX4h0M2jHBhmSfRE=\ngolang.org/x/net v0.34.0 h1:Mb7Mrk043xzHgnRM88suvJFwzVrRfHEHJEl5/71CKw0=\ngolang.org/x/net v0.34.0/go.mod h1:di0qlW3YNM5oh6GqDGQr92MyTozJPmybPK4Ev/Gm31k=\ngolang.org/x/sys v0.29.0 h1:TPYlXGxvx1MGTn2GiZDhnjPA9wZzZeGKHHmKhHYvgaU=\ngolang.org/x/sys v0.29.0/go.mod h1:/VUhepiaJMQUp4+oa/7Zr1D23ma6VTLIYjOOTFZPUcA=\ngolang.org/x/text v0.21.0 h1:zyQAAkrwaneQ066sspRyJaG9VNi/YJ1NfzcGB3hZ/qo=\ngolang.org/x/text v0.21.0/go.mod h1:4IBbMaMmOPCJ8SecivzSH54+73PCFmPWxNTLm+vZkEQ=\ngoogle.golang.org/genproto/googleapis/rpc v0.0.0-20250115164207-1a7da9e5054f h1:OxYkA3wjPsZyBylwymxSHa7ViiW1Sml4ToBrncvFehI=\ngoogle.golang.org/genproto/googleapis/rpc v0.0.0-20250115164207-1a7da9e5054f/go.mod h1:+2Yz8+CLJbIfL9z73EW45avw8Lmge3xVElCP9zEKi50=\ngoogle.golang.org/grpc v1.71.1 h1:ffsFWr7ygTUscGPI0KKK6TLrGz0476KUvvsbqWK0rPI=\ngoogle.golang.org/grpc v1.71.1/go.mod h1:H0GRtasmQOh9LkFoCPDu3ZrwUtD1YGE+b2vYBYd/8Ec=\ngoogle.golang.org/protobuf v1.36.6 h1:z1NpPI8ku2WgiWnf+t9wTPsn6eP1L7ksHUlkfLvd9xY=\ngoogle.golang.org/protobuf v1.36.6/go.mod h1:jduwjTPXsFjZGTmRluh+L6NjiWu7pchiJ2/5YcXBHnY=\n`;
}

function goMain(moduleName) {
  return `package main\n\nimport (\n\t\"context\"\n\t\"encoding/json\"\n\t\"fmt\"\n\n\tcoresdk \"${moduleName}/GoSdk\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tinputJSON, err := coresdk.Parameter.GetInputJSONString(ctx)\n\tif err != nil {\n\t\tpanic(err)\n\t}\n\tvar input map[string]interface{}\n\t_ = json.Unmarshal([]byte(inputJSON), &input)\n\n\turl := \"\"\n\tif startUrls, ok := input[\"startUrls\"].([]interface{}); ok && len(startUrls) > 0 {\n\t\tif first, ok := startUrls[0].(map[string]interface{}); ok {\n\t\t\turl, _ = first[\"url\"].(string)\n\t\t}\n\t}\n\tif singleURL, ok := input[\"url\"].(string); ok && singleURL != \"\" {\n\t\turl = singleURL\n\t}\n\n\t_, _ = coresdk.Result.SetTableHeader(ctx, []*coresdk.TableHeaderItem{\n\t\t{Label: \"URL\", Key: \"url\", Format: \"text\"},\n\t\t{Label: \"Status\", Key: \"status\", Format: \"text\"},\n\t\t{Label: \"Title\", Key: \"title\", Format: \"text\"},\n\t})\n\t_, _ = coresdk.Log.Info(ctx, fmt.Sprintf(\"Processing %s\", url))\n\trow, _ := json.Marshal(map[string]string{\"url\": url, \"status\": \"success\", \"title\": \"Example Domain\"})\n\t_, _ = coresdk.Result.PushData(ctx, string(row))\n}\n`;
}
