import fs from 'node:fs';
import path from 'node:path';
import { CliError } from '../utils/errors.js';
import { repoRoot } from '../utils/paths.js';

const SUPPORTED_LANGUAGES = new Set(['python', 'node', 'go']);

export async function initCommand(target = '.', options = {}) {
  const language = normalizeLanguage(options.language ?? options.lang ?? 'python');
  const projectDir = path.resolve(process.cwd(), target);

  if (fs.existsSync(projectDir) && fs.readdirSync(projectDir).length > 0 && !options.force) {
    throw new CliError(`Target directory is not empty: ${projectDir}. Use --force to write into it.`);
  }

  fs.mkdirSync(projectDir, { recursive: true });
  copyTemplateSdk(language, projectDir);
  writeTemplateProject(language, projectDir, options.name ?? path.basename(projectDir));

  console.log(`Created ${language} CoreClaw worker: ${projectDir}`);
  console.log(`Next: coreclaw run ${projectDir}`);
  return projectDir;
}

function normalizeLanguage(language) {
  const value = String(language).toLowerCase();
  if (value === 'js' || value === 'javascript' || value === 'nodejs') {
    return 'node';
  }
  if (!SUPPORTED_LANGUAGES.has(value)) {
    throw new CliError(`Unsupported language "${language}". Use python, node, or go.`);
  }
  return value;
}

function copyTemplateSdk(language, projectDir) {
  const sourceDir = path.join(repoRoot, 'templates', language);
  copyDir(sourceDir, projectDir);
}

function copyDir(sourceDir, targetDir) {
  for (const entry of fs.readdirSync(sourceDir, { withFileTypes: true })) {
    const source = path.join(sourceDir, entry.name);
    const target = path.join(targetDir, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(target, { recursive: true });
      copyDir(source, target);
    } else if (entry.isFile()) {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.copyFileSync(source, target);
    }
  }
}

function writeTemplateProject(language, projectDir, name) {
  writeJson(path.join(projectDir, 'input_schema.json'), {
    description: `${name} CoreClaw worker`,
    b: 'startUrls',
    properties: [
      {
        title: 'Start URLs',
        name: 'startUrls',
        type: 'array',
        editor: 'requestList',
        description: 'URLs to process.',
        default: [{ url: 'https://example.com' }],
        required: true,
      },
    ],
  });

  writeJson(path.join(projectDir, 'output_schema.json'), [
    { name: 'url', type: 'string', description: 'URL' },
    { name: 'status', type: 'string', description: 'Status' },
    { name: 'title', type: 'string', description: 'Title' },
  ]);

  if (language === 'python') {
    writeIfMissing(path.join(projectDir, 'requirements.txt'), 'grpcio>=1.71.0\nprotobuf>=5.29.0\n');
    writeIfMissing(path.join(projectDir, 'README.md'), readme(name, 'python'));
    writeIfMissing(path.join(projectDir, 'main.py'), pythonMain());
  } else if (language === 'node') {
    writeJson(path.join(projectDir, 'package.json'), {
      name: slugify(name),
      version: '0.1.0',
      private: true,
      main: 'main.js',
      scripts: { start: 'node main.js' },
      dependencies: {
        '@grpc/grpc-js': '^1.14.3',
        'google-protobuf': '^4.0.2',
      },
    });
    writeIfMissing(path.join(projectDir, 'README.md'), readme(name, 'node'));
    writeIfMissing(path.join(projectDir, 'main.js'), nodeMain());
  } else if (language === 'go') {
    writeIfMissing(path.join(projectDir, 'go.mod'), `module ${slugify(name)}\n\ngo 1.23\n\nrequire google.golang.org/grpc v1.71.1\nrequire google.golang.org/protobuf v1.36.6\n`);
    writeIfMissing(path.join(projectDir, 'go.sum'), '');
    writeIfMissing(path.join(projectDir, 'README.md'), readme(name, 'go'));
    writeIfMissing(path.join(projectDir, 'main.go'), goMain(slugify(name)));
  }
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, `${JSON.stringify(value, null, 2)}\n`, 'utf8');
}

function writeIfMissing(filePath, content) {
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content, 'utf8');
  }
}

function slugify(value) {
  const slug = String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  return slug || 'coreclaw-worker';
}

function readme(name, language) {
  return `# ${name}\n\nGenerated by CoreClaw CLI.\n\n## Local Run\n\n\`\`\`bash\ncoreclaw run .\n\`\`\`\n\n## Upload Package\n\n\`\`\`bash\ncoreclaw pack .\n\`\`\`\n\nLanguage: ${language}\n`;
}

function pythonMain() {
  return `#!/usr/bin/env python3\nimport asyncio\nfrom sdk import CoreSDK\n\n\nasync def run():\n    input_json = CoreSDK.Parameter.get_input_json_dict()\n    url = input_json.get(\"url\") or (input_json.get(\"startUrls\", [{}])[0].get(\"url\") if input_json.get(\"startUrls\") else \"\")\n\n    CoreSDK.Result.set_table_header([\n        {\"label\": \"URL\", \"key\": \"url\", \"format\": \"text\"},\n        {\"label\": \"Status\", \"key\": \"status\", \"format\": \"text\"},\n        {\"label\": \"Title\", \"key\": \"title\", \"format\": \"text\"},\n    ])\n    CoreSDK.Log.info(f\"Processing {url}\")\n    CoreSDK.Result.push_data({\"url\": url, \"status\": \"success\", \"title\": \"Example Domain\"})\n\n\nif __name__ == \"__main__\":\n    asyncio.run(run())\n`;
}

function nodeMain() {
  return `const coresdk = require('./sdk')\n\nasync function main() {\n  const input = await coresdk.parameter.getInputJSONObject()\n  const url = input.url || (Array.isArray(input.startUrls) && input.startUrls[0] ? input.startUrls[0].url : '')\n\n  await coresdk.result.setTableHeader([\n    { label: 'URL', key: 'url', format: 'text' },\n    { label: 'Status', key: 'status', format: 'text' },\n    { label: 'Title', key: 'title', format: 'text' },\n  ])\n  await coresdk.log.info(\`Processing \${url}\`)\n  await coresdk.result.pushData({ url, status: 'success', title: 'Example Domain' })\n}\n\nmain().catch(async (error) => {\n  try { await coresdk.log.error(error.stack || error.message) } catch {}\n  process.exitCode = 1\n})\n`;
}

function goMain(moduleName) {
  return `package main\n\nimport (\n\t\"context\"\n\t\"encoding/json\"\n\t\"fmt\"\n\n\tcoresdk \"${moduleName}/GoSdk\"\n)\n\nfunc main() {\n\tctx := context.Background()\n\tinputJSON, err := coresdk.Parameter.GetInputJSONString(ctx)\n\tif err != nil {\n\t\tpanic(err)\n\t}\n\tvar input map[string]interface{}\n\t_ = json.Unmarshal([]byte(inputJSON), &input)\n\n\turl := \"\"\n\tif startUrls, ok := input[\"startUrls\"].([]interface{}); ok && len(startUrls) > 0 {\n\t\tif first, ok := startUrls[0].(map[string]interface{}); ok {\n\t\t\turl, _ = first[\"url\"].(string)\n\t\t}\n\t}\n\tif singleURL, ok := input[\"url\"].(string); ok && singleURL != \"\" {\n\t\turl = singleURL\n\t}\n\n\t_, _ = coresdk.Result.SetTableHeader(ctx, []*coresdk.TableHeaderItem{\n\t\t{Label: \"URL\", Key: \"url\", Format: \"text\"},\n\t\t{Label: \"Status\", Key: \"status\", Format: \"text\"},\n\t\t{Label: \"Title\", Key: \"title\", Format: \"text\"},\n\t})\n\t_, _ = coresdk.Log.Info(ctx, fmt.Sprintf(\"Processing %s\", url))\n\trow, _ := json.Marshal(map[string]string{\"url\": url, \"status\": \"success\", \"title\": \"Example Domain\"})\n\t_, _ = coresdk.Result.PushData(ctx, string(row))\n}\n`;
}
